% =========================================================================
% Stage 1 Step 5 — Discrete Trajectory Control & Multi-Move Indexing
% Project 2: STM32 Automated Precision Indexing & Feed Control
% =========================================================================
% Objective: Programmatically construct, validate, and simulate the discrete-time
% (Ts = 1 ms) profiled closed-loop position control system featuring:
% 1. Kinematic Trapezoidal Profile Generator (a_max = 50 rad/s^2, w_max = 8 rad/s)
% 2. 1000 CPR Incremental Encoder Quantized Feedback (0.36 deg resolution)
% 3. Averaged PWM H-Bridge Actuator Model (V_dc = 12.0 V)
% 4. Discrete PID Controller with Backward Euler Filter (N=100) & Conditional Anti-Windup
% 5. Configurable Physical Feedforward Compensation (Kff_v, Kff_a)
% 6. Multi-Move Sequential Indexing Simulation (3x 90 deg steps over 1.50 s)
% 7. Dual Tracking Error Evaluation (True Physical e_true vs Encoder-Observed e_enc)
% =========================================================================

clear; clc; close all;

% 1. Load Parameter Definitions
scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(scriptDir);
addpath(scriptDir);
params;

% 2. Define Model Paths
modelsDir = fullfile(projectRoot, 'models');
resultsDir = fullfile(projectRoot, 'results', 'stage1');
if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

modelName = 'stage1_profiled_loop_model';
modelPath = fullfile(modelsDir, [modelName '.slx']);

% Step 1-4 Baseline Model Paths for Regression Checks
step1ModelName = 'stage1_motor_plant';
step2ModelName = 'stage1_encoder_model';
step3ModelName = 'stage1_pwm_model';
step4ModelName = 'stage1_closed_loop_model';

step1ModelPath = fullfile(modelsDir, [step1ModelName '.slx']);
step2ModelPath = fullfile(modelsDir, [step2ModelName '.slx']);
step3ModelPath = fullfile(modelsDir, [step3ModelName '.slx']);
step4ModelPath = fullfile(modelsDir, [step4ModelName '.slx']);

% 3. Preload Simulink Engine
disp('Preloading Simulink engine...');
load_system('simulink');

% 4. Create New Simulink Model (Overwrite if existing)
disp(['Creating Stage 1 Step 5 Simulink model structure (' modelName '.slx)...']);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
new_system(modelName);
open_system(modelName);

% 5. Configure Model Solver Properties
set_param(modelName, 'SolverType', 'Variable-step');
set_param(modelName, 'Solver', 'ode45');
set_param(modelName, 'StopTime', num2str(t_stop));
set_param(modelName, 'SaveOutput', 'on');
set_param(modelName, 'SignalLogging', 'on');

% 6. Add Blocks to Model
% --- Simulation Clock ---
add_block('simulink/Sources/Clock', [modelName '/Clock'], ...
    'Position', [30, 100, 60, 120]);

% --- Mode Selector Constants (move_mode: 1=Single, 2=3x Sequential; ff_mode: 0=Off, 1=On) ---
add_block('simulink/Sources/Constant', [modelName '/Move_Mode_Constant'], ...
    'Value', '1', ...
    'Position', [30, 140, 60, 160]);

add_block('simulink/Sources/Constant', [modelName '/FF_Mode_Constant'], ...
    'Value', '0', ...
    'Position', [30, 180, 60, 200]);

% --- Trapezoidal Profile Generator (MATLAB Function) ---
profGenBlock = [modelName '/Trapezoidal_Profile_Generator'];
add_block('simulink/User-Defined Functions/MATLAB Function', profGenBlock, ...
    'Position', [90, 95, 170, 165]);

rt = sfroot;
chartProf = rt.find('-isa', 'Stateflow.EMChart', 'Path', profGenBlock);
chartProf(1).Script = sprintf([ ...
    'function [theta_ref, w_ref, a_ref] = Trapezoidal_Profile_Generator(t, mode)\n' ...
    '%% Kinematic Trapezoidal Profile Generator for Stage 1 Step 5\n' ...
    'a_max = 50.0; %% rad/s^2\n' ...
    'w_max = 8.0;  %% rad/s\n' ...
    'step_rad = 90.0 * pi / 180; %% 1.5707963 rad\n' ...
    't_a = w_max / a_max; %% 0.160 s\n' ...
    'theta_a = 0.5 * a_max * t_a^2; %% 0.640 rad\n' ...
    't_c = (step_rad - 2 * theta_a) / w_max; %% 0.0363495 s\n' ...
    't_f = 2 * t_a + t_c; %% 0.3563495 s\n' ...
    '\n' ...
    'if mode == 1 %% Single 90 deg Indexing Move\n' ...
    '    t_start = 0.050;\n' ...
    '    [theta_ref, w_ref, a_ref] = calc_single_move(t, t_start, step_rad, a_max, w_max, t_a, theta_a, t_c, t_f);\n' ...
    'else %% 3x Sequential 90 deg Indexing Moves (0 -> 90 -> 180 -> 270 deg)\n' ...
    '    t_start1 = 0.050;\n' ...
    '    t_start2 = 0.500;\n' ...
    '    t_start3 = 0.950;\n' ...
    '    [th1, w1, a1] = calc_single_move(t, t_start1, step_rad, a_max, w_max, t_a, theta_a, t_c, t_f);\n' ...
    '    [th2, w2, a2] = calc_single_move(t, t_start2, step_rad, a_max, w_max, t_a, theta_a, t_c, t_f);\n' ...
    '    [th3, w3, a3] = calc_single_move(t, t_start3, step_rad, a_max, w_max, t_a, theta_a, t_c, t_f);\n' ...
    '    theta_ref = th1 + th2 + th3;\n' ...
    '    w_ref = w1 + w2 + w3;\n' ...
    '    a_ref = a1 + a2 + a3;\n' ...
    'end\n' ...
    'end\n' ...
    '\n' ...
    'function [th, w, a] = calc_single_move(t, t_start, step_rad, a_max, w_max, t_a, theta_a, t_c, t_f)\n' ...
    'if t < t_start\n' ...
    '    th = 0.0; w = 0.0; a = 0.0;\n' ...
    'elseif t < t_start + t_a\n' ...
    '    dt = t - t_start;\n' ...
    '    th = 0.5 * a_max * dt^2;\n' ...
    '    w = a_max * dt;\n' ...
    '    a = a_max;\n' ...
    'elseif t < t_start + t_a + t_c\n' ...
    '    dt = t - t_start - t_a;\n' ...
    '    th = theta_a + w_max * dt;\n' ...
    '    w = w_max;\n' ...
    '    a = 0.0;\n' ...
    'elseif t < t_start + t_f\n' ...
    '    dt = t_start + t_f - t;\n' ...
    '    th = step_rad - 0.5 * a_max * dt^2;\n' ...
    '    w = a_max * dt;\n' ...
    '    a = -a_max;\n' ...
    'else\n' ...
    '    th = step_rad;\n' ...
    '    w = 0.0;\n' ...
    '    a = 0.0;\n' ...
    'end\n' ...
    'end\n']);

% --- Discrete Zero-Order Hold Sinks for Trajectory ---
add_block('simulink/Discrete/Zero-Order Hold', [modelName '/ZOH_Reference'], ...
    'SampleTime', 'Ts_disc', ...
    'Position', [190, 100, 220, 120]);

add_block('simulink/Discrete/Zero-Order Hold', [modelName '/ZOH_Wref'], ...
    'SampleTime', 'Ts_disc', ...
    'Position', [190, 130, 220, 150]);

add_block('simulink/Discrete/Zero-Order Hold', [modelName '/ZOH_Aref'], ...
    'SampleTime', 'Ts_disc', ...
    'Position', [190, 160, 220, 180]);

% --- Discrete Closed-Loop Error Junction (e_enc = theta_ref - theta_enc) ---
add_block('simulink/Math Operations/Sum', [modelName '/Sum_Discrete_Error'], ...
    'Inputs', '+-', ...
    'Position', [250, 100, 270, 120]);

% --- Discrete Closed-Loop True Error Junction (e_true = theta_ref - theta_true) ---
add_block('simulink/Math Operations/Sum', [modelName '/Sum_True_Error'], ...
    'Inputs', '+-', ...
    'Position', [250, 40, 270, 60]);

% --- Discrete Zero-Order Hold on Encoder Feedback ---
add_block('simulink/Discrete/Zero-Order Hold', [modelName '/ZOH_Feedback'], ...
    'SampleTime', 'Ts_disc', ...
    'Position', [250, 220, 280, 240]);

% --- Discrete PID + Configurable Feedforward Controller (MATLAB Function) ---
pidBlock = [modelName '/Discrete_PID_Controller'];
add_block('simulink/User-Defined Functions/MATLAB Function', pidBlock, ...
    'Position', [310, 100, 400, 180]);

chartPid = rt.find('-isa', 'Stateflow.EMChart', 'Path', pidBlock);
chartPid(1).Script = sprintf([ ...
    'function d = Discrete_PID_Controller(e, w_ref, a_ref, ff_mode)\n' ...
    '%% Corrected Discrete PID Controller (Ts = 1 ms) - Validated Optimization\n' ...
    '%% Kp=0.50, Ki=8.00, Kd=0.0000, N=20 with Conditional Anti-Windup Clamping\n' ...
    'if ff_mode == 0 %% Phase 1 Unassisted Baseline Failed Configuration\n' ...
    '    Kp = 2.50;\n' ...
    '    Ki = 0.50;\n' ...
    '    Kd = 0.080;\n' ...
    '    N  = 100;\n' ...
    '    Kff_v = 0.0;\n' ...
    '    Kff_a = 0.0;\n' ...
    'else %% Phase 2 Corrected & Validated Optimized Feedforward Configuration\n' ...
    '    Kp = 0.50;\n' ...
    '    Ki = 8.00;\n' ...
    '    Kd = 0.0000;\n' ...
    '    N  = 20;\n' ...
    '    Kff_v = 0.004175;             %% (Ke + R*B/Kt) / V_dc\n' ...
    '    Kff_a = 0.00000834;           %% (J*R/Kt + L*B/Kt) / V_dc\n' ...
    'end\n' ...
    'Ts = 0.001;\n' ...
    '\n' ...
    'persistent u_i u_d e_prev\n' ...
    'if isempty(u_i)\n' ...
    '    u_i = 0.0;\n' ...
    '    u_d = 0.0;\n' ...
    '    e_prev = 0.0;\n' ...
    'end\n' ...
    '\n' ...
    '%% 1. Discrete Proportional Term\n' ...
    'u_p = Kp * e;\n' ...
    '\n' ...
    '%% 2. Discrete Derivative Term (Backward Euler with Filter N)\n' ...
    'u_d = (Kd * N * (e - e_prev) + u_d) / (1.0 + N * Ts);\n' ...
    '\n' ...
    '%% 3. Tentative Discrete Integrator Update\n' ...
    'v_i = u_i + Ki * Ts * e;\n' ...
    '\n' ...
    '%% 4. Explicit Configurable Feedforward Term\n' ...
    'if ff_mode == 1\n' ...
    '    u_ff = Kff_v * w_ref + Kff_a * a_ref;\n' ...
    'else\n' ...
    '    u_ff = 0.0;\n' ...
    'end\n' ...
    '\n' ...
    '%% 5. Total Tentative Control Output u_calc\n' ...
    'u_calc = u_p + v_i + u_d + u_ff;\n' ...
    '\n' ...
    '%% 6. Actuator Duty Cycle Saturation [0.0, 1.0]\n' ...
    'if u_calc > 1.0\n' ...
    '    d = 1.0;\n' ...
    'elseif u_calc < 0.0\n' ...
    '    d = 0.0;\n' ...
    'else\n' ...
    '    d = u_calc;\n' ...
    'end\n' ...
    '\n' ...
    '%% 7. Conditional Integration Anti-Windup Clamping\n' ...
    'is_sat_high = (u_calc > 1.0) && (e > 0);\n' ...
    'is_sat_low  = (u_calc < 0.0) && (e < 0);\n' ...
    'if is_sat_high || is_sat_low\n' ...
    '    u_i = u_i;\n' ...
    'else\n' ...
    '    u_i = v_i;\n' ...
    'end\n' ...
    '\n' ...
    'e_prev = e;\n' ...
    'end\n']);

% --- Averaged PWM H-Bridge Gain ---
add_block('simulink/Math Operations/Gain', [modelName '/Gain_Vdc'], ...
    'Gain', 'V_dc', ...
    'Position', [430, 130, 470, 160]);

% --- Electromechanical Motor Plant (Preserved Baseline Dynamics) ---
add_block('simulink/Math Operations/Sum', [modelName '/Sum_Electrical'], ...
    'Inputs', '+--', ...
    'Position', [500, 130, 520, 160]);

add_block('simulink/Math Operations/Gain', [modelName '/Gain_InvL'], ...
    'Gain', '1/L', ...
    'Position', [540, 130, 580, 160]);

add_block('simulink/Continuous/Integrator', [modelName '/Integrator_Current'], ...
    'InitialCondition', '0', ...
    'Position', [610, 130, 640, 160]);

add_block('simulink/Math Operations/Gain', [modelName '/Gain_R'], ...
    'Gain', 'R', ...
    'Orientation', 'left', ...
    'Position', [550, 190, 590, 220]);

add_block('simulink/Math Operations/Gain', [modelName '/Gain_Ke'], ...
    'Gain', 'Ke', ...
    'Orientation', 'left', ...
    'Position', [550, 250, 590, 280]);

add_block('simulink/Math Operations/Gain', [modelName '/Gain_Kt'], ...
    'Gain', 'Kt', ...
    'Position', [680, 130, 720, 160]);

add_block('simulink/Sources/Constant', [modelName '/Load_Torque_TL'], ...
    'Value', 'TL', ...
    'Position', [720, 70, 750, 100]);

add_block('simulink/Math Operations/Sum', [modelName '/Sum_Mechanical'], ...
    'Inputs', '+--', ...
    'Position', [750, 130, 770, 160]);

add_block('simulink/Math Operations/Gain', [modelName '/Gain_InvJ'], ...
    'Gain', '1/J', ...
    'Position', [800, 130, 840, 160]);

add_block('simulink/Continuous/Integrator', [modelName '/Integrator_Speed'], ...
    'InitialCondition', '0', ...
    'Position', [870, 130, 900, 160]);

add_block('simulink/Math Operations/Gain', [modelName '/Gain_B'], ...
    'Gain', 'B', ...
    'Orientation', 'left', ...
    'Position', [800, 210, 840, 240]);

add_block('simulink/Continuous/Integrator', [modelName '/Integrator_Position'], ...
    'InitialCondition', '0', ...
    'Position', [940, 130, 970, 160]);

% --- Step 2 Incremental Encoder Path ---
add_block('simulink/Math Operations/Gain', [modelName '/Gain_RadToCounts'], ...
    'Gain', 'CPR/(2*pi)', ...
    'Position', [1010, 130, 1060, 160]);

add_block('simulink/Math Operations/Rounding Function', [modelName '/Encoder_Quantizer'], ...
    'Operator', 'floor', ...
    'Position', [1090, 130, 1130, 160]);

add_block('simulink/Math Operations/Gain', [modelName '/Gain_CountsToRad'], ...
    'Gain', '(2*pi)/CPR', ...
    'Position', [1160, 130, 1210, 160]);

% --- To Workspace Logging Sinks ---
add_block('simulink/Sinks/To Workspace', [modelName '/ToWorkspace_theta_ref'], ...
    'VariableName', 'sim_theta_ref', 'SaveFormat', 'Timeseries', ...
    'Position', [240, 70, 290, 90]);

add_block('simulink/Sinks/To Workspace', [modelName '/ToWorkspace_e_true'], ...
    'VariableName', 'sim_e_true', 'SaveFormat', 'Timeseries', ...
    'Position', [290, 40, 340, 60]);

add_block('simulink/Sinks/To Workspace', [modelName '/ToWorkspace_e_enc'], ...
    'VariableName', 'sim_e_enc', 'SaveFormat', 'Timeseries', ...
    'Position', [300, 70, 350, 90]);

add_block('simulink/Sinks/To Workspace', [modelName '/ToWorkspace_d'], ...
    'VariableName', 'sim_d', 'SaveFormat', 'Timeseries', ...
    'Position', [450, 40, 500, 60]);

add_block('simulink/Sinks/To Workspace', [modelName '/ToWorkspace_Veff'], ...
    'VariableName', 'sim_Veff', 'SaveFormat', 'Timeseries', ...
    'Position', [520, 40, 570, 60]);

add_block('simulink/Sinks/To Workspace', [modelName '/ToWorkspace_i'], ...
    'VariableName', 'sim_i', 'SaveFormat', 'Timeseries', ...
    'Position', [650, 40, 700, 60]);

add_block('simulink/Sinks/To Workspace', [modelName '/ToWorkspace_w'], ...
    'VariableName', 'sim_w', 'SaveFormat', 'Timeseries', ...
    'Position', [920, 40, 970, 60]);

add_block('simulink/Sinks/To Workspace', [modelName '/ToWorkspace_theta_true'], ...
    'VariableName', 'sim_theta_true', 'SaveFormat', 'Timeseries', ...
    'Position', [990, 40, 1040, 60]);

add_block('simulink/Sinks/To Workspace', [modelName '/ToWorkspace_counts'], ...
    'VariableName', 'sim_counts', 'SaveFormat', 'Timeseries', ...
    'Position', [1140, 40, 1190, 60]);

add_block('simulink/Sinks/To Workspace', [modelName '/ToWorkspace_theta_enc'], ...
    'VariableName', 'sim_theta_enc', 'SaveFormat', 'Timeseries', ...
    'Position', [1240, 130, 1290, 150]);

% 7. Connect Signal Lines
add_line(modelName, 'Clock/1', 'Trapezoidal_Profile_Generator/1', 'autorouting', 'on');
add_line(modelName, 'Move_Mode_Constant/1', 'Trapezoidal_Profile_Generator/2', 'autorouting', 'on');

add_line(modelName, 'Trapezoidal_Profile_Generator/1', 'ZOH_Reference/1', 'autorouting', 'on');
add_line(modelName, 'Trapezoidal_Profile_Generator/2', 'ZOH_Wref/1', 'autorouting', 'on');
add_line(modelName, 'Trapezoidal_Profile_Generator/3', 'ZOH_Aref/1', 'autorouting', 'on');

add_line(modelName, 'ZOH_Reference/1', 'Sum_Discrete_Error/1', 'autorouting', 'on');
add_line(modelName, 'ZOH_Reference/1', 'Sum_True_Error/1', 'autorouting', 'on');
add_line(modelName, 'ZOH_Reference/1', 'ToWorkspace_theta_ref/1', 'autorouting', 'on');

add_line(modelName, 'Sum_True_Error/1', 'ToWorkspace_e_true/1', 'autorouting', 'on');

add_line(modelName, 'Sum_Discrete_Error/1', 'Discrete_PID_Controller/1', 'autorouting', 'on');
add_line(modelName, 'Sum_Discrete_Error/1', 'ToWorkspace_e_enc/1', 'autorouting', 'on');

add_line(modelName, 'ZOH_Wref/1', 'Discrete_PID_Controller/2', 'autorouting', 'on');
add_line(modelName, 'ZOH_Aref/1', 'Discrete_PID_Controller/3', 'autorouting', 'on');
add_line(modelName, 'FF_Mode_Constant/1', 'Discrete_PID_Controller/4', 'autorouting', 'on');

add_line(modelName, 'Discrete_PID_Controller/1', 'Gain_Vdc/1', 'autorouting', 'on');
add_line(modelName, 'Discrete_PID_Controller/1', 'ToWorkspace_d/1', 'autorouting', 'on');

add_line(modelName, 'Gain_Vdc/1', 'Sum_Electrical/1', 'autorouting', 'on');
add_line(modelName, 'Gain_Vdc/1', 'ToWorkspace_Veff/1', 'autorouting', 'on');

add_line(modelName, 'Sum_Electrical/1', 'Gain_InvL/1', 'autorouting', 'on');
add_line(modelName, 'Gain_InvL/1', 'Integrator_Current/1', 'autorouting', 'on');
add_line(modelName, 'Integrator_Current/1', 'Gain_R/1', 'autorouting', 'on');
add_line(modelName, 'Gain_R/1', 'Sum_Electrical/2', 'autorouting', 'on');
add_line(modelName, 'Integrator_Current/1', 'Gain_Kt/1', 'autorouting', 'on');
add_line(modelName, 'Integrator_Current/1', 'ToWorkspace_i/1', 'autorouting', 'on');

add_line(modelName, 'Gain_Kt/1', 'Sum_Mechanical/1', 'autorouting', 'on');
add_line(modelName, 'Load_Torque_TL/1', 'Sum_Mechanical/3', 'autorouting', 'on');

add_line(modelName, 'Sum_Mechanical/1', 'Gain_InvJ/1', 'autorouting', 'on');
add_line(modelName, 'Gain_InvJ/1', 'Integrator_Speed/1', 'autorouting', 'on');
add_line(modelName, 'Integrator_Speed/1', 'Gain_B/1', 'autorouting', 'on');
add_line(modelName, 'Gain_B/1', 'Sum_Mechanical/2', 'autorouting', 'on');
add_line(modelName, 'Integrator_Speed/1', 'Gain_Ke/1', 'autorouting', 'on');
add_line(modelName, 'Gain_Ke/1', 'Sum_Electrical/3', 'autorouting', 'on');
add_line(modelName, 'Integrator_Speed/1', 'Integrator_Position/1', 'autorouting', 'on');
add_line(modelName, 'Integrator_Speed/1', 'ToWorkspace_w/1', 'autorouting', 'on');

add_line(modelName, 'Integrator_Position/1', 'Sum_True_Error/2', 'autorouting', 'on');
add_line(modelName, 'Integrator_Position/1', 'ToWorkspace_theta_true/1', 'autorouting', 'on');
add_line(modelName, 'Integrator_Position/1', 'Gain_RadToCounts/1', 'autorouting', 'on');

add_line(modelName, 'Gain_RadToCounts/1', 'Encoder_Quantizer/1', 'autorouting', 'on');
add_line(modelName, 'Encoder_Quantizer/1', 'ToWorkspace_counts/1', 'autorouting', 'on');
add_line(modelName, 'Encoder_Quantizer/1', 'Gain_CountsToRad/1', 'autorouting', 'on');
add_line(modelName, 'Gain_CountsToRad/1', 'ToWorkspace_theta_enc/1', 'autorouting', 'on');

add_line(modelName, 'Gain_CountsToRad/1', 'ZOH_Feedback/1', 'autorouting', 'on');
add_line(modelName, 'ZOH_Feedback/1', 'Sum_Discrete_Error/2', 'autorouting', 'on');

% 8. Save Step 5 Model
save_system(modelName, modelPath);
disp(['Stage 1 Step 5 model saved successfully to: ' modelPath]);

% 9. Run Simulation Phase 1: Pure Feedback Baseline Discrete PID (ff_mode = 0, t_stop = 0.50 s)
disp('Running Simulation Phase 1: Pure Feedback Baseline Discrete PID (ff_mode = 0)...');
set_param([modelName '/Move_Mode_Constant'], 'Value', '1');
set_param([modelName '/FF_Mode_Constant'], 'Value', '0');
set_param(modelName, 'StopTime', num2str(t_stop));
save_system(modelName, modelPath);
simOut_base = sim(modelName);

% 10. Run Simulation Phase 2: Feedforward-Enhanced Discrete PID (ff_mode = 1, t_stop = 0.50 s)
disp('Running Simulation Phase 2: Feedforward-Enhanced Discrete PID (ff_mode = 1)...');
set_param([modelName '/FF_Mode_Constant'], 'Value', '1');
save_system(modelName, modelPath);
simOut_ff = sim(modelName);

% 11. Run Simulation Test Case 2: 3x Sequential 90 deg Indexing Moves (ff_mode = 1, move_mode = 2, t_stop = 1.50 s)
disp('Running Simulation Test Case 2: 3x Sequential 90 deg Indexing Moves (mode = 2, t_stop = 1.50 s)...');
set_param([modelName '/Move_Mode_Constant'], 'Value', '2');
set_param([modelName '/FF_Mode_Constant'], 'Value', '1');
set_param(modelName, 'StopTime', num2str(t_stop_seq));
save_system(modelName, modelPath);
simOut_seq = sim(modelName);

% Revert Model Blocks Back to Default (move_mode = 1, ff_mode = 1, StopTime = 0.50 s)
set_param([modelName '/Move_Mode_Constant'], 'Value', '1');
set_param([modelName '/FF_Mode_Constant'], 'Value', '1');
set_param(modelName, 'StopTime', num2str(t_stop));
save_system(modelName, modelPath);

% 12. Run Baseline Protection Checks on Step 1, Step 2, Step 3, and Step 4 Models
disp('Running Baseline Protection Check (confirming Step 1, 2, 3, and 4 models remain intact)...');
load_system(step1ModelPath); sim(step1ModelName);
load_system(step2ModelPath); sim(step2ModelName);
load_system(step3ModelPath); sim(step3ModelName);
load_system(step4ModelPath); sim(step4ModelName);

% 13. Data Extraction & Quantitative Performance Verification
% --- Phase 1 Baseline Arrays ---
t_base = simOut_base.sim_theta_ref.Time;
theta_ref_base = simOut_base.sim_theta_ref.Data;
e_true_base = simOut_base.sim_e_true.Data;
e_enc_base = simOut_base.sim_e_enc.Data;
d_base = simOut_base.sim_d.Data;
i_base = simOut_base.sim_i.Data;
w_base = simOut_base.sim_w.Data;
theta_true_base = simOut_base.sim_theta_true.Data;
theta_enc_base = simOut_base.sim_theta_enc.Data;

% --- Phase 2 Feedforward-Enhanced Arrays ---
t_vec = simOut_ff.sim_theta_ref.Time;
theta_ref_vec = simOut_ff.sim_theta_ref.Data;
e_true_vec = simOut_ff.sim_e_true.Data;
e_enc_vec = simOut_ff.sim_e_enc.Data;
d_vec = simOut_ff.sim_d.Data;
Veff_vec = simOut_ff.sim_Veff.Data;
i_vec = simOut_ff.sim_i.Data;
w_vec = simOut_ff.sim_w.Data;
theta_true_vec = simOut_ff.sim_theta_true.Data;
counts_vec = simOut_ff.sim_counts.Data;
theta_enc_vec = simOut_ff.sim_theta_enc.Data;

% --- Test Case 2 Sequential Arrays ---
t_seq_vec = simOut_seq.sim_theta_ref.Time;
theta_ref_seq = simOut_seq.sim_theta_ref.Data;
e_true_seq = simOut_seq.sim_e_true.Data;
e_enc_seq = simOut_seq.sim_e_enc.Data;
d_seq = simOut_seq.sim_d.Data;
i_seq = simOut_seq.sim_i.Data;
w_seq = simOut_seq.sim_w.Data;
theta_true_seq = simOut_seq.sim_theta_true.Data;
theta_enc_seq = simOut_seq.sim_theta_enc.Data;

% Performance Calculations
% Phase 1 Baseline Metrics
base_max_duty = max(d_base);
base_peak_current = max(abs(i_base));
base_max_e_true_deg = max(abs(e_true_base)) * 180 / pi;
base_max_e_enc_deg = max(abs(e_enc_base)) * 180 / pi;
base_ss_e_true_deg = abs(theta_ref_base(end) - theta_true_base(end)) * 180 / pi;
base_ss_e_enc_deg = abs(theta_ref_base(end) - theta_enc_base(end)) * 180 / pi;

% Phase 2 Feedforward Metrics
max_duty_cycle = max(d_vec);
peak_current = max(abs(i_vec));
max_e_true_deg = max(abs(e_true_vec)) * 180 / pi;
max_e_enc_deg = max(abs(e_enc_vec)) * 180 / pi;

ss_e_true_rad = abs(theta_ref_vec(end) - theta_true_vec(end));
ss_e_true_deg = ss_e_true_rad * 180 / pi;
ss_e_enc_rad = abs(theta_ref_vec(end) - theta_enc_vec(end));
ss_e_enc_deg = ss_e_enc_rad * 180 / pi;

% Profile completion time and settling time calculation
t_prof_end = 0.050 + t_f_prof; % 0.4063495 s
post_prof_idx = find(t_vec >= t_prof_end);
if isempty(post_prof_idx)
    t_settling = 0.0;
else
    settled_sub = find(abs(theta_true_vec(post_prof_idx) - theta_ref_val) <= 0.02 * theta_ref_val, 1, 'first');
    if isempty(settled_sub)
        t_settling = t_vec(end) - t_prof_end;
    else
        t_settling = t_vec(post_prof_idx(settled_sub)) - t_prof_end;
    end
end

% Test Case 2 Sequential 3x Move Accuracy
seq_target_deg = 270.0;
seq_final_true_deg = theta_true_seq(end) * 180 / pi;
seq_final_enc_deg = theta_enc_seq(end) * 180 / pi;
seq_err_true_deg = abs(seq_target_deg - seq_final_true_deg);
seq_err_enc_deg = abs(seq_target_deg - seq_final_enc_deg);

disp('====================================================');
disp('STAGE 1 STEP 5 EMPIRICAL SIMULINK METRICS REPORT');
disp('====================================================');
fprintf('--- PHASE 1: UNASSISTED BASELINE DISCRETE PID ---\n');
fprintf('  Max Duty Cycle d(t)            : %.4f\n', base_max_duty);
fprintf('  Peak Armature Current i_peak   : %.4f A\n', base_peak_current);
fprintf('  Max True Tracking Error        : %.4f deg\n', base_max_e_true_deg);
fprintf('  Max Encoder Tracking Error     : %.4f deg\n', base_max_e_enc_deg);
fprintf('  Steady-State True Error        : %.4f deg\n', base_ss_e_true_deg);
fprintf('  Steady-State Encoder Error     : %.4f deg\n\n', base_ss_e_enc_deg);

fprintf('--- PHASE 2: FEEDFORWARD-ENHANCED DISCRETE PID ---\n');
fprintf('  1. Actuator Saturation Check  : d_max = %.4f (Bound [0, 1]) -> %s\n', ...
    max_duty_cycle, check_pass(max_duty_cycle <= 1.0 && min(d_vec) >= 0.0));
fprintf('  2. Peak Armature Current      : i_peak = %.4f A (Limit <= 1.5000 A) -> %s\n', ...
    peak_current, check_pass(peak_current <= 1.5000));
fprintf('  3. Max True Tracking Error    : |e_true|_max = %.4f deg (Limit <= 1.7200 deg) -> %s\n', ...
    max_e_true_deg, check_pass(max_e_true_deg <= 1.7200));
fprintf('  4. Max Encoder Tracking Error : |e_enc|_max = %.4f deg (Limit <= 1.7200 deg) -> %s\n', ...
    max_e_enc_deg, check_pass(max_e_enc_deg <= 1.7200));
fprintf('  5. Final True Position Error  : |e_true(t_stop)| = %.4f deg (Limit <= 0.3600 deg) -> %s\n', ...
    ss_e_true_deg, check_pass(ss_e_true_deg <= 0.3600));
fprintf('  6. Final Encoder Pos Error    : |e_enc(t_stop)| = %.4f deg (Limit <= 0.3600 deg / 1 count) -> %s\n', ...
    ss_e_enc_deg, check_pass(ss_e_enc_deg <= 0.3600));
fprintf('  7. Profile Completion Time    : t_prof_end = %.4f s\n', t_prof_end);
fprintf('  8. Post-Profile Settling Time : t_s = %.4f s (Limit <= 0.0200 s) -> %s\n', ...
    t_settling, check_pass(t_settling <= 0.0200));
fprintf('  9. 3x Sequential Indexing (270 deg Target at 1.50 s):\n');
fprintf('     Final True Position        : %.4f deg (Error: %.4f deg) -> %s\n', ...
    seq_final_true_deg, seq_err_true_deg, check_pass(seq_err_true_deg <= 0.3600));
fprintf('     Final Encoder Position     : %.4f deg (Error: %.4f deg) -> %s\n', ...
    seq_final_enc_deg, seq_err_enc_deg, check_pass(seq_err_enc_deg <= 0.3600));
disp('====================================================');

% 14. Save Workspace Data to MAT File
matPath = fullfile(resultsDir, 'stage5_data.mat');
save(matPath, ...
    't_base', 'theta_ref_base', 'e_true_base', 'e_enc_base', 'd_base', 'i_base', 'w_base', 'theta_true_base', 'theta_enc_base', ...
    't_vec', 'theta_ref_vec', 'e_true_vec', 'e_enc_vec', 'd_vec', 'Veff_vec', 'i_vec', 'w_vec', 'theta_true_vec', 'counts_vec', 'theta_enc_vec', ...
    't_seq_vec', 'theta_ref_seq', 'e_true_seq', 'e_enc_seq', 'd_seq', 'i_seq', 'w_seq', 'theta_true_seq', 'theta_enc_seq', ...
    'max_duty_cycle', 'peak_current', 'max_e_true_deg', 'max_e_enc_deg', 'ss_e_true_deg', 'ss_e_enc_deg', ...
    't_prof_end', 't_settling', 'seq_target_deg', 'seq_final_true_deg', 'seq_final_enc_deg', ...
    'base_max_duty', 'base_peak_current', 'base_max_e_true_deg', 'base_max_e_enc_deg', 'base_ss_e_true_deg', 'base_ss_e_enc_deg');

disp(['Exported raw simulation data to: ' matPath]);
disp('Stage 1 Step 5 build and simulation execution completed.');

function str = check_pass(cond)
    if cond
        str = 'PASS';
    else
        str = 'FAIL';
    end
end
